import torch

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# Model Params
IMG_SIZE = 128
GRID_SIZE = 32
SPLATS_PER_CELL = 4
PARAMS_PER_SPLAT = 9
TOTAL_CHANNELS = SPLATS_PER_CELL * PARAMS_PER_SPLAT


#ENCODER TRAINING PARAMS

SPLAT_ENCODER_BASE_BATCH_SIZE = 4
SPLAT_ENCODER_ACCUM_STEPS = 4  #steps over which gradient will be accumulated so effective batch size is 4*4=16
SPLAT_ENCODER_WARMUP_EPOCHS = 50
SPLAT_ENCODER_POLISH_EPOCHS = 100
SPLAT_ENCODER_STARTING_LR = 1e-3
SPLAT_ENCODER_POLISH_LR = 2e-4
SPLAT_ENCODER_VGG_LOSS_RAT = 0.8
SPLAT_ENCODER_MSE_LOSS_RAT = 0.2
SPLAT_ENCODER_TRAINING_SAVE_DIR = "splat_encoder_training_imgs"